# Generated by Django 5.0 on 2023-12-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Qnt',
            new_name='qnt',
        ),
    ]
